### ISSUE TITLE
Some tools do not support Chinese

### ISSUE THREAD

**Issue by chenwei0930** [CorentinTh/it-tools#1092]
### Describe the bug

When inputting Chinese characters in the "Base64 String Encoding/Decoding" tool to convert them into Base64 encoding, the input box disappears. The F12 console reports an error：
DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at u (https://tools.datapipe.top/assets/base64-94c6bba0.js:1:52)
    at Pg.fn (https://tools.datapipe.top/assets/base64-string-converter-a0adcec4.js:1:616)
    at Pg.run (https://tools.datapipe.top/assets/index-55fd01d4.js:1:5553)
    at get value (https://tools.datapipe.top/assets/index-55fd01d4.js:1:14322)
    at M (https://tools.datapipe.top/assets/index-55fd01d4.js:1:12921)
    at https://tools.datapipe.top/assets/base64-string-converter-a0adcec4.js:1:1405
    at o (https://tools.datapipe.top/assets/index-55fd01d4.js:1:17413)
    at ln (https://tools.datapipe.top/assets/index-55fd01d4.js:1:26267)
    at Proxy.<anonymous> (https://tools.datapipe.top/assets/index-55fd01d4.js:1389:41913)
    at Ap (https://tools.datapipe.top/assets/index-55fd01d4.js:1:17725)

### What happened?

A bug happened!

### System information

Win10 Chrome version: 124.0.6367.201

### Where did you encounter the bug?

A self hosted

**Comment by sharevb** [comment]
Hi @chenwei0930, fixed in #905

**Comment by CorentinTh** [comment]
Solved in #905
