### ISSUE TITLE
[OTHER] Build Failed

### ISSUE THREAD

**Issue by aladdin-im** [CorentinTh/it-tools#760]
Build Failed

```bash
[+] Building 19.8s (10/14)                                                                                                                               
 => [internal] load build definition from Dockerfile                                                                                                0.0s
 => => transferring dockerfile: 534B                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                   0.0s
 => => transferring context: 34B                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/nginx:stable-alpine                                                                             15.7s
 => [internal] load metadata for docker.io/library/node:lts-alpine                                                                                 15.7s
 => [build-stage 1/6] FROM docker.io/library/node:lts-alpine@sha256:0e071f3c5c84cffa6b1035023e1956cf28d48f4b36e229cef328772da81ec0c5                0.0s
 => [internal] load build context                                                                                                                   0.1s
 => => transferring context: 91.44kB                                                                                                                0.1s
 => CACHED [production-stage 1/3] FROM docker.io/library/nginx:stable-alpine@sha256:74694f2de64c44787a81f0554aa45b281e468c0c58b8665fafceda624d31e5  0.0s
 => CACHED [build-stage 2/6] WORKDIR /app                                                                                                           0.0s
 => CACHED [build-stage 3/6] COPY package.json pnpm-lock.yaml ./                                                                                    0.0s
 => ERROR [build-stage 4/6] RUN npm install -g pnpm && pnpm i --frozen-lockfile                                                                     3.9s
------                                                                                                                                                   
 > [build-stage 4/6] RUN npm install -g pnpm && pnpm i --frozen-lockfile:                                                                                
#10 1.616 npm WARN EBADENGINE Unsupported engine {                                                                                                       
#10 1.616 npm WARN EBADENGINE   package: 'pnpm@8.10.5',                                                                                                  
#10 1.616 npm WARN EBADENGINE   required: { node: '>=16.14' },                                                                                           
#10 1.616 npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.1.2' }
#10 1.618 npm WARN EBADENGINE }
#10 3.876 
#10 3.876 added 1 package, and audited 2 packages in 3s
#10 3.876 
#10 3.876 1 package is looking for funding
#10 3.876   run `npm fund` for details
#10 3.877 
#10 3.877 found 0 vulnerabilities
#10 3.907 ERROR: This version of pnpm requires at least Node.js v16.14
#10 3.907 The current version of Node.js is v16.13.1
#10 3.907 Visit https://r.pnpm.io/comp to see the list of past pnpm versions with respective Node.js version support.
------
executor failed running [/bin/sh -c npm install -g pnpm && pnpm i --frozen-lockfile]: exit code: 1
```

I change node version
```dockerfile
...
FROM node:16.14.2-alpine AS build-stage
...
```

still getting error

```bash
[+] Building 111.6s (13/15)                                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                                0.0s
 => => transferring dockerfile: 538B                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                   0.0s
 => => transferring context: 34B                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/nginx:stable-alpine                                                                             15.4s
 => [internal] load metadata for docker.io/library/node:16.14.2-alpine                                                                             17.5s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                         0.0s
 => [build-stage 1/6] FROM docker.io/library/node:16.14.2-alpine@sha256:28bed508446db2ee028d08e76fb47b935defa26a84986ca050d2596ea67fd506            0.0s
 => [internal] load build context                                                                                                                   0.1s
 => => transferring context: 37.14kB                                                                                                                0.0s
 => CACHED [production-stage 1/3] FROM docker.io/library/nginx:stable-alpine@sha256:74694f2de64c44787a81f0554aa45b281e468c0c58b8665fafceda624d31e5  0.0s
 => CACHED [build-stage 2/6] WORKDIR /app                                                                                                           0.0s
 => CACHED [build-stage 3/6] COPY package.json pnpm-lock.yaml ./                                                                                    0.0s
 => CACHED [build-stage 4/6] RUN npm install -g pnpm && pnpm i --frozen-lockfile                                                                    0.0s
 => [build-stage 5/6] COPY . .                                                                                                                      0.1s
 => ERROR [build-stage 6/6] RUN pnpm build                                                                                                         93.8s
------
 > [build-stage 6/6] RUN pnpm build:
#13 0.578 
#13 0.578 > it-tools@2023.11.2-7d94e11 build /app
#13 0.578 > vue-tsc --noEmit && NODE_OPTIONS=--max_old_space_size=4096 vite build
#13 0.578 
#13 6.717 vite v4.4.9 building for production...
#13 6.877 transforming...
#13 24.43 [plugin:vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "/app/node_modules/.pnpm/bcryptjs@2.4.3/node_modules/bcryptjs/dist/bcrypt.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
#13 24.63 [plugin:vite:resolve] Module "path" has been externalized for browser compatibility, imported by "/app/node_modules/.pnpm/mime-types@2.1.35/node_modules/mime-types/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
#13 31.03 [plugin:vite:resolve] Module "tls" has been externalized for browser compatibility, imported by "/app/node_modules/.pnpm/pdf-signature-reader@1.4.2/node_modules/pdf-signature-reader/helpers/verification.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
#13 93.69  ELIFECYCLE  Command failed.
------
executor failed running [/bin/sh -c pnpm build]: exit code: 1
```

**Comment by boomboomxx** [comment]
see node version in [package.json](https://github.com/CorentinTh/it-tools/blob/b430baef4099a6004c66ad798f3a5a3455122fb6/package.json#L111) and upgrade your basic image version if needed

**Comment by sharevb** [comment]
Hi @aladdin-im @boomboomxx if you are interested in an up to date version of it-tools, with many improvements, new tools, and bug fixes, as this repo is almost no more maintained, I made a fork here : https://github.com/sharevb/it-tools (https://sharevb-it-tools.vercel.app/ and docker images https://github.com/sharevb/it-tools/pkgs/container/it-tools)

**Comment by olegshulyakov** [comment]
`pnpm install` fails with Docker `lts-alpine` image:
```
/web/it-tools # npx pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +1308
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading monaco-editor@0.43.0: 16.78 MB/16.78 MB, done
Progress: resolved 1308, reused 269, downloaded 1039, added 1039, done
node_modules/.pnpm/vue-demi@0.13.11_vue@3.3.4/node_modules/vue-demi: Running postinstall script...
node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild: Running postinstall script, failed in 225ms
.../esbuild@0.23.1/node_modules/esbuild postinstall$ node install.js
│ node:internal/child_process:1120
│     result.error = new ErrnoException(result.error, 'spawnSync ' + options.file);
│                    ^
│ <ref *1> Error: spawnSync /web/it-tools/node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild/bi…
│     at Object.spawnSync (node:internal/child_process:1120:20)
│     at spawnSync (node:child_process:911:24)
│     at Object.execFileSync (node:child_process:954:15)
│     at validateBinaryVersion (/web/it-tools/node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuil…
│     at /web/it-tools/node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild/install.js:284:5 {
│   errno: -13,
│   code: 'EACCES',
│   syscall: 'spawnSync /web/it-tools/node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild/bin/es…
│   path: '/web/it-tools/node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild/bin/esbuild',
│   spawnargs: [ '--version' ],
│   error: [Circular *1],
│   status: null,
│   signal: null,
│   output: null,
│   pid: 0,
│   stdout: undefined,
│   stderr: undefined
│ }
│ Node.js v24.13.0
└─ Failed in 227ms at /web/it-tools/node_modules/.pnpm/esbuild@0.23.1/node_modules/esbuild
node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild: Running postinstall script, failed in 238ms
.../esbuild@0.18.20/node_modules/esbuild postinstall$ node install.js
│ node:internal/child_process:1120
│     result.error = new ErrnoException(result.error, 'spawnSync ' + options.file);
│                    ^
│ <ref *1> Error: spawnSync /web/it-tools/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/b…
│     at Object.spawnSync (node:internal/child_process:1120:20)
│     at spawnSync (node:child_process:911:24)
│     at Object.execFileSync (node:child_process:954:15)
│     at validateBinaryVersion (/web/it-tools/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbui…
│     at /web/it-tools/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/install.js:285:5 {
│   errno: -13,
│   code: 'EACCES',
│   syscall: 'spawnSync /web/it-tools/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/bin/e…
│   path: '/web/it-tools/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/bin/esbuild',
│   spawnargs: [ '--version' ],
│   error: [Circular *1],
│   status: null,
│   signal: null,
│   output: null,
│   pid: 0,
│   stdout: undefined,
│   stderr: undefined
│ }
│ Node.js v24.13.0
└─ Failed in 238ms at /web/it-tools/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild
node_modules/.pnpm/vue-demi@0.14.5_vue@3.3.4/node_modules/vue-demi: Running postinstall script...
 ELIFECYCLE  Command failed with exit code 1.
```
