### ISSUE TITLE
[BUG] Base64 string encoder/decoder may be have an error

### ISSUE THREAD

**Issue by projoy** [CorentinTh/it-tools#879]
Thank you very much for your IT-TOOLS, it's really good!!
When using the "Base64 string encoder/decoder",  I encountered a problem. 
In the "String to encode" section, when entering Chinese characters, an error occurs.

**To Reproduce**

1. Go to 'Base64 string encoder/decoder'
2. Go to 'String to encode'
3. Enter any Chinese characters, such as "你好"

The page will then display an error, the exception in console as follows:

DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at u (http://192.168.1.10:13001/assets/base64-94c6bba0.js:1:52)
    at Qh.fn (http://192.168.1.10:13001/assets/base64-string-converter-5cdd91b3.js:1:645)
    at Qh.run (http://192.168.1.10:13001/assets/index-3141604a.js:1:5554)
    at get value (http://192.168.1.10:13001/assets/index-3141604a.js:1:14323)
    at N (http://192.168.1.10:13001/assets/index-3141604a.js:1:12922)
    at http://192.168.1.10:13001/assets/base64-string-converter-5cdd91b3.js:1:1474
    at o (http://192.168.1.10:13001/assets/index-3141604a.js:1:17414)
    at Io (http://192.168.1.10:13001/assets/index-3141604a.js:1:26477)
    at Proxy.<anonymous> (http://192.168.1.10:13001/assets/index-3141604a.js:1253:15586)
    at hf (http://192.168.1.10:13001/assets/index-3141604a.js:1:17726)

**Comment by sharevb** [comment]
Hi @jasoncheng7115 and @CorentinTh, fixed in #905
