### ISSUE TITLE
[BUG] PDF signature checker fails to validate eIDAS signatures/stamps

### ISSUE THREAD

**Issue by PovilasID** [CorentinTh/it-tools#937]
**Which tool is impacted?**
PDF signature checker

**To Reproduce**
Upload a PDF signed with Qualified electronic signature the PDF part of UI will crash with.

```
index-d4d1dfb2.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at Proxy.<anonymous> (pdf-signature-checke…ee1b79.js:3049:3460)
    at Sp (index-d4d1dfb2.js:1:17725)
    at Tg.we [as fn] (index-d4d1dfb2.js:1:41586)
    at Tg.run (index-d4d1dfb2.js:1:5553)
    at Y.L.update (index-d4d1dfb2.js:1:42353)
    at Zi (index-d4d1dfb2.js:1:14513)
    at o2 (index-d4d1dfb2.js:1:16145)
```
and the UI will disappear.

**Expected behavior**
Validation if it validated ideally listing the date of signing and or some details like authority providing the validation.
Here is what adobe displays:
![image](https://github.com/CorentinTh/it-tools/assets/396243/d6c5a205-568c-4ad6-b358-68bde7f81420)

**Screenshots**

**Configuration (please complete the following information):**

- Device: PC
- OS: Windows
- Browser Chrome
- Version Version 122.0.6261.112 

**Additional context**
[About signature](https://en.wikipedia.org/wiki/Qualified_electronic_signature)
[Sample doc for testing](https://www.dokobit.com/docs/pricing/Dokobit-el-pasirasymo-sprendimu-kainodara.pdf) It it e 'stamp' not a signature but uses same protocol so it will work for this.

**Comment by sharevb** [comment]
Will prepare a PR for a fix

**Comment by sharevb** [comment]
Hi @CorentinTh and @PovilasID, fixed in #967

**Comment by sharevb** [comment]
Hi, for people interested in up to date version of it-tools, I made kind of a fork here : https://github.com/sharevb/it-tools (https://sharevb-it-tools.vercel.app/ and docker images https://github.com/sharevb/it-tools/pkgs/container/it-tools)

**Comment by sharevb** [comment]
Hi @PovilasID , fixed here: https://sharevb-it-tools.vercel.app/pdf-signature-checker

And if you are interested in an up to date version of it-tools, with many improvements, new tools, and bug fixes, as this repo is almost no more maintained, I made a fork here : https://github.com/sharevb/it-tools (https://sharevb-it-tools.vercel.app/ and docker images https://github.com/sharevb/it-tools/pkgs/container/it-tools)
